### ISSUE TITLE
learn to use for and range()

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/python-learning#3]
Try out the following in the interactive python terminal. (You will need to press enter twice after each).

```
 for i in range(7): print(i)
 for i in range(0, 10): print(i)
 for i in range(-5, 6): print(i)
 for i in range(10, 1): print(i)
 for i in range(10, 1, -1): print(i)
 for i in range(100, 1, -10): print(i)
 for i in range(1, 50, 5): print(i)
```

Study the results carefully and let it help you understand how range works. Using this information, create a folder called called src/ranges and in the create the following scripts.
- countup.py: count from 1 to 10
- countdown.py: count down from 10 to 0
- by2.py: count up from 10 to 30 by 2s
- seesway.py: count from -10 to 10 and then back from 10 to -10
- down-by-3: count down from 75 to 11 by 3s
- upto-0: count from -20 to 0 by 5s

Document you findings regarding the range() function in a wiki page called the range() function. Document the input parameters. Indicate whether or not they are required. Also document the return type of this function. You may want to write other programs and/or tests in the interactive python shell in order to get all the required information. To find out the return type of the function you can use:

```
>>> type(range(10))
```

**Comment by Prince-linux** [comment]
I am finding difficulty in solving seesway.py please help out.

**Comment by lcabrini** [comment]
To solve seesaw, you just need to think in two steps. First count up from -10 to 10. When you are done, create  another loop to count back down again.
