### ISSUE TITLE
Write a program that asks the user for two numbers and adds them.

### ISSUE THREAD

**Issue by lcabrini** [Prince-linux/python-learning#4]
This issue depends on #3 

Write a program that asks the user to enter two numbers and prints out their sum. Use input to read in the input from the user. Place the program in src/add and call it add.py.

Run the program and input 51 and 32 as input numbers. What result do you get? Was it what you expected? If not, what do you think happened?

Based on your results, create a wiki page called The input() function, and document how input() works. Document the input parameter(s) and the return type.

**Comment by Prince-linux** [comment]
I have created the wiki page.
